### ISSUE TITLE
Request to have our own whitelist

### ISSUE THREAD

**Issue by stretchnz** [gaul/desktop-everywhere#5]
Any chance we can use our own list of sites?

**Comment by gaul** [comment]
How do you envision adding new sites?  Something in the browser or an external file?

**Comment by stretchnz** [comment]
I am not bothered either way, if I know where the file would be on the phone I am happy / confident to edit that directly if need be.
Thanks for the instant response!

**Comment by gaul** [comment]
Does [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/) better serve your needs?  I would like to focus Desktop Everywhere just on redirecting well-known mobile sites.

**Comment by stretchnz** [comment]
Sounds like it would suit indeed.
Fair call, thanks again I will go that direction.
