### ISSUE TITLE
It breaks all links in reddit notification e-mails. They redirect to the main page. A blacklist would be nice.

### ISSUE THREAD

**Issue by mzso** [gaul/desktop-everywhere#9]
Hi!

This is annoying. At first I thought reddit was broken, but after I disabled the extension, the links work.
To bad, I can't do it selectively for the site.

**Comment by gaul** [comment]
Can you share specifically which kind of links don't work?

**Comment by mzso** [comment]
> 
> 
> Can you share specifically which kind of links don't work?

Sorry. I think I might have rushed to a conclusion, due to coincidentally doing something differently when I disabled the extension. It seems like if I middle click links in gmail it works, but if I just left click them I get redirected to the main page.
I can't determine why. Maybe a reddit bug after all. Or some gmail nonsense.

(BTW they're are these sort of clunky urls: https://click.redditmail.com/CL0/https:%2F%2Fwww.reddit.com%2Fr%2FAskPhysics%2Fcomments%2Fltz288%2Fcan_a_superefficient_incandescent_lightbulb_be%2Fgp4pxlc%2F%3F$deep_link=true%26correlation_id=51b99c46-9258-4951-a6f4-c1e8873ae0b2%26ref=email_post_reply%26ref_campaign=email_post_reply%26ref_source=email/3/01000177e7312325-18a0ec88-df6b-4e05-abcd-e64856051a7a-000000/2H69FpDDfRy_L9s0cWx7mt3xg6WrAEO4s0Bwhg7xUuQ=182 )
